version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1111
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress
  wordpress:
    depends_on: 
      - db
    image: wordpress
    restart: always
    ports:
      - 1000:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: 1111
    networks:
      - wordpress
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 2000:80
    networks:
      - wordpress
networks:
  wordpress:
volumes:
  db_data: